CREATE TYPE "public"."bet_status" AS ENUM('PENDING', 'COMMITTED', 'RESOLVED', 'CLAIMED', 'TIMEOUT', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."game_type" AS ENUM('FLIP_IT', 'FIGHT_CLUB', 'DEGEN_DERBY', 'SHADOW_POKER');--> statement-breakpoint
CREATE TYPE "public"."outcome" AS ENUM('HEADS', 'TAILS', 'PLAYER_WIN', 'HOUSE_WIN', 'DRAW');--> statement-breakpoint
CREATE TABLE "house-fun-app_bet" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "house-fun-app_bet_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"betPda" varchar(44) NOT NULL,
	"transactionSignature" varchar(88),
	"playerId" integer,
	"gameId" integer,
	"amount" bigint NOT NULL,
	"status" "bet_status" DEFAULT 'PENDING' NOT NULL,
	"playerChoice" integer,
	"commitmentHash" varchar(64),
	"nonce" bigint,
	"outcome" "outcome",
	"playerWon" boolean,
	"payoutAmount" bigint,
	"houseFee" bigint,
	"placedAt" timestamp with time zone NOT NULL,
	"committedAt" timestamp with time zone,
	"resolvedAt" timestamp with time zone,
	"claimedAt" timestamp with time zone,
	"commitSlot" bigint,
	"resolveSlot" bigint,
	CONSTRAINT "house-fun-app_bet_betPda_unique" UNIQUE("betPda")
);
--> statement-breakpoint
CREATE TABLE "house-fun-app_game_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "house-fun-app_game_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"gameId" integer NOT NULL,
	"sessionPda" varchar(44),
	"status" varchar(20) DEFAULT 'WAITING',
	"minPlayers" integer DEFAULT 2,
	"maxPlayers" integer DEFAULT 6,
	"entryFee" bigint,
	"prizePool" bigint DEFAULT 0,
	"playerIds" json,
	"winnerId" integer,
	"createdAt" timestamp with time zone NOT NULL,
	"startedAt" timestamp with time zone,
	"endedAt" timestamp with time zone,
	CONSTRAINT "house-fun-app_game_session_sessionPda_unique" UNIQUE("sessionPda")
);
--> statement-breakpoint
CREATE TABLE "house-fun-app_game" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "house-fun-app_game_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" "game_type" NOT NULL,
	"name" varchar(64) NOT NULL,
	"description" text,
	"minBet" bigint DEFAULT 1000000,
	"maxBet" bigint DEFAULT 100000000000,
	"houseEdgeBps" integer DEFAULT 100,
	"isActive" boolean DEFAULT true,
	"totalBets" bigint DEFAULT 0,
	"totalVolume" bigint DEFAULT 0,
	"totalHouseProfit" bigint DEFAULT 0,
	"programId" varchar(44),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "house-fun-app_house_treasury" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "house-fun-app_house_treasury_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"housePda" varchar(44) NOT NULL,
	"totalFeesCollected" bigint DEFAULT 0,
	"totalWithdrawn" bigint DEFAULT 0,
	"currentBalance" bigint DEFAULT 0,
	"totalBetsProcessed" bigint DEFAULT 0,
	"totalVolume" bigint DEFAULT 0,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "house-fun-app_house_treasury_housePda_unique" UNIQUE("housePda")
);
--> statement-breakpoint
CREATE TABLE "house-fun-app_leaderboard" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "house-fun-app_leaderboard_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"playerId" integer NOT NULL,
	"totalProfitRank" integer,
	"totalWageredRank" integer,
	"winStreakRank" integer,
	"gameStats" json,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "house-fun-app_leaderboard_playerId_unique" UNIQUE("playerId")
);
--> statement-breakpoint
CREATE TABLE "house-fun-app_player" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "house-fun-app_player_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"walletAddress" varchar(44) NOT NULL,
	"username" varchar(32),
	"totalBets" integer DEFAULT 0,
	"totalWagered" bigint DEFAULT 0,
	"totalWon" bigint DEFAULT 0,
	"totalLost" bigint DEFAULT 0,
	"netProfit" bigint DEFAULT 0,
	"favoriteGame" "game_type",
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"lastLoginAt" timestamp with time zone,
	CONSTRAINT "house-fun-app_player_walletAddress_unique" UNIQUE("walletAddress")
);
--> statement-breakpoint
CREATE TABLE "house-fun-app_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "house-fun-app_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "house-fun-app_treasury_transaction" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "house-fun-app_treasury_transaction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"treasuryId" integer NOT NULL,
	"type" varchar(20) NOT NULL,
	"amount" bigint NOT NULL,
	"transactionSignature" varchar(88),
	"betId" integer,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "house-fun-app_bet" ADD CONSTRAINT "house-fun-app_bet_playerId_house-fun-app_player_id_fk" FOREIGN KEY ("playerId") REFERENCES "public"."house-fun-app_player"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "house-fun-app_bet" ADD CONSTRAINT "house-fun-app_bet_gameId_house-fun-app_game_id_fk" FOREIGN KEY ("gameId") REFERENCES "public"."house-fun-app_game"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "house-fun-app_game_session" ADD CONSTRAINT "house-fun-app_game_session_gameId_house-fun-app_game_id_fk" FOREIGN KEY ("gameId") REFERENCES "public"."house-fun-app_game"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "house-fun-app_game_session" ADD CONSTRAINT "house-fun-app_game_session_winnerId_house-fun-app_player_id_fk" FOREIGN KEY ("winnerId") REFERENCES "public"."house-fun-app_player"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "house-fun-app_leaderboard" ADD CONSTRAINT "house-fun-app_leaderboard_playerId_house-fun-app_player_id_fk" FOREIGN KEY ("playerId") REFERENCES "public"."house-fun-app_player"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "house-fun-app_treasury_transaction" ADD CONSTRAINT "house-fun-app_treasury_transaction_treasuryId_house-fun-app_house_treasury_id_fk" FOREIGN KEY ("treasuryId") REFERENCES "public"."house-fun-app_house_treasury"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "house-fun-app_treasury_transaction" ADD CONSTRAINT "house-fun-app_treasury_transaction_betId_house-fun-app_bet_id_fk" FOREIGN KEY ("betId") REFERENCES "public"."house-fun-app_bet"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "bet_pda_idx" ON "house-fun-app_bet" USING btree ("betPda");--> statement-breakpoint
CREATE INDEX "bet_player_idx" ON "house-fun-app_bet" USING btree ("playerId");--> statement-breakpoint
CREATE INDEX "bet_game_idx" ON "house-fun-app_bet" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "bet_status_idx" ON "house-fun-app_bet" USING btree ("status");--> statement-breakpoint
CREATE INDEX "bet_placed_at_idx" ON "house-fun-app_bet" USING btree ("placedAt");--> statement-breakpoint
CREATE INDEX "bet_tx_idx" ON "house-fun-app_bet" USING btree ("transactionSignature");--> statement-breakpoint
CREATE INDEX "session_game_idx" ON "house-fun-app_game_session" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "session_status_idx" ON "house-fun-app_game_session" USING btree ("status");--> statement-breakpoint
CREATE INDEX "session_pda_idx" ON "house-fun-app_game_session" USING btree ("sessionPda");--> statement-breakpoint
CREATE INDEX "game_type_idx" ON "house-fun-app_game" USING btree ("type");--> statement-breakpoint
CREATE INDEX "game_active_idx" ON "house-fun-app_game" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "wallet_address_idx" ON "house-fun-app_player" USING btree ("walletAddress");--> statement-breakpoint
CREATE INDEX "username_idx" ON "house-fun-app_player" USING btree ("username");--> statement-breakpoint
CREATE INDEX "name_idx" ON "house-fun-app_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "treasury_tx_treasury_idx" ON "house-fun-app_treasury_transaction" USING btree ("treasuryId");--> statement-breakpoint
CREATE INDEX "treasury_tx_type_idx" ON "house-fun-app_treasury_transaction" USING btree ("type");--> statement-breakpoint
CREATE INDEX "treasury_tx_signature_idx" ON "house-fun-app_treasury_transaction" USING btree ("transactionSignature");