-- Migration: Add game tables for house.fun casino
-- Generated manually for Flip It game integration

-- Create enums
DO $$ BEGIN
    CREATE TYPE game_type AS ENUM ('FLIP_IT', 'FIGHT_CLUB', 'DEGEN_DERBY', 'SHADOW_POKER');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE bet_status AS ENUM ('PENDING', 'COMMITTED', 'RESOLVED', 'CLAIMED', 'TIMEOUT', 'CANCELLED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE outcome AS ENUM ('HEADS', 'TAILS', 'PLAYER_WIN', 'HOUSE_WIN', 'DRAW');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Players table
CREATE TABLE IF NOT EXISTS "house-fun-app_player" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "wallet_address" varchar(44) NOT NULL UNIQUE,
    "username" varchar(32),
    "total_bets" integer DEFAULT 0,
    "total_wagered" bigint DEFAULT 0,
    "total_won" bigint DEFAULT 0,
    "total_lost" bigint DEFAULT 0,
    "net_profit" bigint DEFAULT 0,
    "favorite_game" game_type,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone,
    "last_login_at" timestamp with time zone
);

CREATE INDEX IF NOT EXISTS "wallet_address_idx" ON "house-fun-app_player" ("wallet_address");
CREATE INDEX IF NOT EXISTS "username_idx" ON "house-fun-app_player" ("username");

-- Games table
CREATE TABLE IF NOT EXISTS "house-fun-app_game" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "type" game_type NOT NULL,
    "name" varchar(64) NOT NULL,
    "description" text,
    "min_bet" bigint DEFAULT 1000000,
    "max_bet" bigint DEFAULT 100000000000,
    "house_edge_bps" integer DEFAULT 100,
    "is_active" boolean DEFAULT true,
    "total_bets" bigint DEFAULT 0,
    "total_volume" bigint DEFAULT 0,
    "total_house_profit" bigint DEFAULT 0,
    "program_id" varchar(44),
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone
);

CREATE INDEX IF NOT EXISTS "game_type_idx" ON "house-fun-app_game" ("type");
CREATE INDEX IF NOT EXISTS "game_active_idx" ON "house-fun-app_game" ("is_active");

-- Bets table
CREATE TABLE IF NOT EXISTS "house-fun-app_bet" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "bet_pda" varchar(44) NOT NULL UNIQUE,
    "transaction_signature" varchar(88),
    "player_id" integer REFERENCES "house-fun-app_player"("id"),
    "game_id" integer REFERENCES "house-fun-app_game"("id"),
    "amount" bigint NOT NULL,
    "status" bet_status DEFAULT 'PENDING' NOT NULL,
    "player_choice" integer,
    "commitment_hash" varchar(64),
    "nonce" bigint,
    "outcome" outcome,
    "player_won" boolean,
    "payout_amount" bigint,
    "house_fee" bigint,
    "placed_at" timestamp with time zone DEFAULT now() NOT NULL,
    "committed_at" timestamp with time zone,
    "resolved_at" timestamp with time zone,
    "claimed_at" timestamp with time zone,
    "commit_slot" bigint,
    "resolve_slot" bigint
);

CREATE INDEX IF NOT EXISTS "bet_pda_idx" ON "house-fun-app_bet" ("bet_pda");
CREATE INDEX IF NOT EXISTS "bet_player_idx" ON "house-fun-app_bet" ("player_id");
CREATE INDEX IF NOT EXISTS "bet_game_idx" ON "house-fun-app_bet" ("game_id");
CREATE INDEX IF NOT EXISTS "bet_status_idx" ON "house-fun-app_bet" ("status");
CREATE INDEX IF NOT EXISTS "bet_placed_at_idx" ON "house-fun-app_bet" ("placed_at");
CREATE INDEX IF NOT EXISTS "bet_tx_idx" ON "house-fun-app_bet" ("transaction_signature");

-- Game Sessions table
CREATE TABLE IF NOT EXISTS "house-fun-app_game_session" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "game_id" integer NOT NULL REFERENCES "house-fun-app_game"("id"),
    "session_pda" varchar(44) UNIQUE,
    "status" varchar(20) DEFAULT 'WAITING',
    "min_players" integer DEFAULT 2,
    "max_players" integer DEFAULT 6,
    "entry_fee" bigint,
    "prize_pool" bigint DEFAULT 0,
    "player_ids" json,
    "winner_id" integer REFERENCES "house-fun-app_player"("id"),
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "started_at" timestamp with time zone,
    "ended_at" timestamp with time zone
);

CREATE INDEX IF NOT EXISTS "session_game_idx" ON "house-fun-app_game_session" ("game_id");
CREATE INDEX IF NOT EXISTS "session_status_idx" ON "house-fun-app_game_session" ("status");
CREATE INDEX IF NOT EXISTS "session_pda_idx" ON "house-fun-app_game_session" ("session_pda");

-- House Treasury table
CREATE TABLE IF NOT EXISTS "house-fun-app_house_treasury" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "house_pda" varchar(44) NOT NULL UNIQUE,
    "total_fees_collected" bigint DEFAULT 0,
    "total_withdrawn" bigint DEFAULT 0,
    "current_balance" bigint DEFAULT 0,
    "total_bets_processed" bigint DEFAULT 0,
    "total_volume" bigint DEFAULT 0,
    "updated_at" timestamp with time zone
);

-- Treasury Transactions table
CREATE TABLE IF NOT EXISTS "house-fun-app_treasury_transaction" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "treasury_id" integer NOT NULL REFERENCES "house-fun-app_house_treasury"("id"),
    "type" varchar(20) NOT NULL,
    "amount" bigint NOT NULL,
    "transaction_signature" varchar(88),
    "bet_id" integer REFERENCES "house-fun-app_bet"("id"),
    "description" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "treasury_tx_treasury_idx" ON "house-fun-app_treasury_transaction" ("treasury_id");
CREATE INDEX IF NOT EXISTS "treasury_tx_type_idx" ON "house-fun-app_treasury_transaction" ("type");
CREATE INDEX IF NOT EXISTS "treasury_tx_signature_idx" ON "house-fun-app_treasury_transaction" ("transaction_signature");

-- Leaderboard table
CREATE TABLE IF NOT EXISTS "house-fun-app_leaderboard" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "player_id" integer NOT NULL UNIQUE REFERENCES "house-fun-app_player"("id"),
    "total_profit_rank" integer,
    "total_wagered_rank" integer,
    "win_streak_rank" integer,
    "game_stats" json,
    "updated_at" timestamp with time zone
);

-- Seed data: Insert Flip It game
INSERT INTO "house-fun-app_game" ("type", "name", "description", "min_bet", "max_bet", "house_edge_bps", "program_id")
VALUES (
    'FLIP_IT',
    'Flip It',
    '50/50 Coinflip. Double or Nothing. Provably fair with commit-reveal scheme.',
    1000000,
    100000000000,
    100,
    'Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS'
)
ON CONFLICT DO NOTHING;
